function Build-IRReport {

    try {

        Write-Log "Building incident response report..."

        $metadataFile = Join-Path `
            $root `
            "Metadata\collection_metadata.csv"

        $findingsFile = Join-Path `
            $root `
            "Findings\process_findings.csv"

        $timelineFile = Join-Path `
            $root `
            "Timeline\timeline.csv"

        $reportFile = Join-Path `
            $root `
            "Report\IR_Report.txt"

        $metadata = $null
        $findings = @()
        $timeline = @()

        if (Test-Path $metadataFile) {
            $metadata = Import-Csv $metadataFile
        }

        if (Test-Path $findingsFile) {
            $findings = @(Import-Csv $findingsFile)
        }

        if (Test-Path $timelineFile) {
            $timeline = @(Import-Csv $timelineFile)
        }

        $report = @()

        $report += "=============================================="
        $report += "          WINDOWS IR TOOLKIT REPORT"
        $report += "=============================================="
        $report += ""

        $report += "CASE INFORMATION"
        $report += "----------------------------------------------"

        if ($metadata) {

            $report += "Computer Name    : $($metadata.ComputerName)"
            $report += "User             : $($metadata.UserName)"
            $report += "Collection Time  : $($metadata.CollectionTime)"
            $report += "PowerShell       : $($metadata.PowerShellVersion)"
            $report += "Administrator    : $($metadata.IsAdministrator)"
            $report += "Windows Version  : $($metadata.WindowsVersion)"
            $report += "Windows Build    : $($metadata.WindowsBuild)"
            $report += "Architecture     : $($metadata.OSArchitecture)"
            $report += "Last Boot        : $($metadata.LastBootTime)"
        }

        $report += ""

        $report += "COLLECTION SUMMARY"
        $report += "----------------------------------------------"

        $report += "System           : Collected"
        $report += "Users            : Collected"
        $report += "Processes        : Collected"
        $report += "Network          : Collected"
        $report += "Services         : Collected"
        $report += "Event Logs       : Collected"
        $report += "Sysmon           : Collected"
        $report += "Filesystem       : Collected"
        $report += "Hashes           : Collected"

        $report += ""

        $report += "FINDINGS"
        $report += "----------------------------------------------"

        if ($findings.Count -eq 0) {

            $report += "No findings were generated by the current analytic rules."

        }
        else {

            foreach ($finding in $findings) {

                $report += ""
                $report += "Category    : $($finding.Category)"
                $report += "Severity    : $($finding.Severity)"
                $report += "Indicator   : $($finding.Indicator)"
                $report += "Process     : $($finding.Process)"
                $report += "PID         : $($finding.ProcessId)"
                $report += "Path        : $($finding.Path)"
                $report += "CommandLine : $($finding.CommandLine)"
                $report += "Reason      : $($finding.Reason)"
            }
        }

        $report += ""

        $report += "TIMELINE SUMMARY"
        $report += "----------------------------------------------"

        $report += "Timeline events collected: $($timeline.Count)"

        $report += ""

        $report += "OUTPUT DIRECTORY"
        $report += "----------------------------------------------"
        $report += $root

        $report += ""

        $report += "=============================================="
        $report += "              END OF REPORT"
        $report += "=============================================="

        $report |
            Out-File `
                -FilePath $reportFile `
                -Encoding UTF8

        Write-Log "Incident response report created."
    }

    catch {

        Write-Log `
            "Report generation failed: $($_.Exception.Message)" `
            "ERROR"
    }
}